server:
  port: 9092
spring:
  profiles:
    active: common,domain
  redis:
    database: 0
    host: localhost
    port: 6379

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    close-timeout: 15s
    in-memory: true
    packages:
      trust-all: true


