spring:
  datasource:
    druid:
      username: root
      password: 1234
      url: jdbc:mysql://localhost:3306/inepp_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update